# Generated by Django 3.2 on 2021-04-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_practiceseeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='group',
        ),
    ]
